# Generated by Django 4.0.3 on 2022-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('groups', models.CharField(choices=[('test', 'test'), ('test_1', 'test_2'), ('test_3', 'test_3'), ('test_4', 'test_4')], max_length=25)),
            ],
            options={
                'verbose_name': 'CreatedUsers',
                'verbose_name_plural': 'CreatedUsers',
            },
        ),
    ]
