# Generated by Django 4.0.3 on 2022-03-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('test', 'test'), ('test_1', 'test_2'), ('test_3', 'test_3'), ('test_4', 'test_4')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='createdusers',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.createdgroup'),
        ),
    ]
