# Generated by Django 4.0.3 on 2022-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_createdgroup_alter_createdusers_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdgroup',
            name='group',
            field=models.CharField(max_length=25),
        ),
    ]
