# Generated by Django 4.0.3 on 2022-03-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_createdgroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdgroup',
            name='group',
            field=models.CharField(choices=[('test', 'test'), ('test_1', 'test_2'), ('test_3', 'test_3'), ('test_4', 'test_4')], max_length=25),
        ),
    ]
