# Generated by Django 4.0.3 on 2022-03-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_createdgroup_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createdgroup',
            options={'verbose_name': 'CreatedGroup', 'verbose_name_plural': "CreatedGroup's"},
        ),
    ]
